name: Terraform Automation (Plan + Apply)

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    name: Terraform Plan or Apply

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init        
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # ──────────────── PLAN (Feature Branch) ────────────────
      - name: Terraform Plan
        if: startsWith(github.ref, 'refs/heads/feature/')
        id: plan
        run: terraform plan -no-color -out=tfplan | tee plan_output.txt

      - name: Upload Plan Output
        if: startsWith(github.ref, 'refs/heads/feature/')
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan_output.txt

      - name: Create or Update Pull Request
        if: startsWith(github.ref, 'refs/heads/feature/')
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Terraform Plan - ${{ github.ref_name }}"
          body: |
            ✅ Terraform plan generated for **${{ github.ref_name }}**

            ```
            $(cat plan_output.txt)
            ```

            Please review the plan before merging.
          base: main
          branch: ${{ github.ref_name }}
          commit-message: "Terraform plan for ${{ github.ref_name }}"
          draft: false
          delete-branch: false
          labels: terraform, auto-pr

      # ──────────────── APPLY (Main Branch) ────────────────
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
